### ISSUE TITLE
open the issue again , mxc not working .

### ISSUE THREAD

**Issue by ajit1310** [StreamAlpha/tvdatafeed#11]
Hi ,
I am using all good credentials ,  it works  for equity .
it works for commodity too ,  but only when exchange is not given .
its not working when "MCX" is given as exchange , please find the screen shot  ,  error are as usual .
![mcx_error](https://user-images.githubusercontent.com/58735112/124347427-635cbf00-dc02-11eb-92e7-83d81839f4a7.PNG)

File "C:\Python\lib\site-packages\tvDatafeed\main.py", line 335, in get_hist
    return self.__create_df(raw_data, symbol)
  File "C:\Python38\lib\site-packages\tvDatafeed\main.py", line 251, in __create_df
    out = re.search('"s":\[(.+?)\}\]', raw_data).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
~m~329~m~{"session_id":"<0.13198.3653>_hkg1-charts-6-webchart-9@hkg1-compute-6_x","timestamp":1625298449,"release":"registry:5000/tvbs_release/webchart:release_204-45","studies_metadata_hash":"8a46abeb53a04396e3f024f9513b546b2459751f","protocol":"json","javastudies":"javastudies-3.60_1429","auth_scheme_vsn":2,"via":"45.135.231.119:443"}
~m~82~m~{"m":"series_loading","p":["cs_mgcyhzvxxpfr","s1","s1",1625298449],"t":1625298449}~m~115~m~{"m":"qsd","p":["qs_gbjgfqdnhlll",{"n":"MCX:NATURALGAS1!","s":"permission_denied","v":{"alternative":"mcx_free"}}]}~m~120~m~{"m":"symbol_error","p":["cs_mgcyhzvxxpfr","symbol_1","permission denied","group","mcx_free",1625298449],"t":1625298449}~m~138~m~{"m":"series_error","p":["cs_mgcyhzvxxpfr","s1","s1","resolve error","hkg1-charts-6-webchart-9@hkg1-compute-6",1625298449],"t":1625298449}~m~420~m~{"m":"qsd","p":["qs_gbjgfqdnhlll",{"n":"MCX:NATURALGAS1!","s":"ok","v":{"update_mode":"streaming","type":"futures","short_name":"NATURALGAS1!","pro_name":"MCX:NATURALGAS1!","pricescale":10,"original_name":"MCX:NATURALGAS1!","minmove2":0,"minmov":1,"language":"hi","is_tradable":true,"fractional":false,"exchange":"MCX","description":"NATURAL GAS FUTURES (CONTINUOUS: CURRENT CONTRACT IN FRONT)","currency_code":"INR"}}]}
~m~4~m~~h~1
~m~4~m~~h~2
~m~4~m~~h~3
~m~4~m~~h~4
~m~4~m~~h~5
~m~4~m~~h~6
~m~4~m~~h~7

**Comment by StreamAlpha** [comment]
fixed login issue, update to latest version using-
`pip install --upgrade --no-cache-dir git+https://github.com/StreamAlpha/tvdatafeed.git`
