### ISSUE TITLE
Not working with username and password

### ISSUE THREAD

**Issue by rahulchigurupati** [StreamAlpha/tvdatafeed#16]
Error in using ChromeDriver, Here is the error message

WARNING:tvDatafeed.main:error Message: session not created: This version of ChromeDriver only supports Chrome version 87 Current browser version is 91.0.4472.124 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe

Working fine with no username and password

**Comment by StreamAlpha** [comment]
delete .tvDatafeed from c:\users\{your_username}\.tvDatafeed
and reinstall from repo
`pip install --upgrade --no-cache-dir git+https://github.com/StreamAlpha/tvdatafeed.git`
