### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by younggotti** [StreamAlpha/tvdatafeed#18]
Hi,
since today I've been getting an error (maybe it depends on the new TV layout):

```
from tvDatafeed import TvDatafeed,Interval
username = 'myuser'
password = 'mypassword'
tv=TvDatafeed(username, password, chromedriver_path=None)
```

returns:
```
error Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="overlap-manager-root"]/div/span/div[1]/div/div/div[1]/div[2]/div"}
  (Session info: headless chrome=92.0.4515.107)

you are using nologin method, data you access may be limited

```

Any help?
Thanks

**Comment by asiletto** [comment]
I have the same problem. Follow.

**Comment by StreamAlpha** [comment]
you will still be able to access limited no of symbols.

**Comment by Dunoo** [comment]
Will there by chance be a fix coming for this anytime soon?

**Comment by StreamAlpha** [comment]
update to latest version and use manual login
`pip install --upgrade --no-cache-dir git+https://github.com/StreamAlpha/tvdatafeed.git`
