### ISSUE TITLE
Unable to fetch data in other time frames

### ISSUE THREAD

**Issue by strikar21** [StreamAlpha/tvdatafeed#20]
`        fetch_data = tv.get_hist(symbol.format(symbol), 'BINANCE', Interval.in_5_minute, 5000)
`returns:
Connection is already closed.
  File "build\bdist.win-amd64\egg\tvfeed\main.py", line 173, in get_hist
  File "build\bdist.win-amd64\egg\tvfeed\main.py", line 89, in __create_df
AttributeError: 'NoneType' object has no attribute 'group'

However if the same code is run with:
`        fetch_data = tv.get_hist(symbol.format(symbol), 'BINANCE', Interval.in_1_minute, 5000)
`returns no errors whatsoever.

I am using the no login method currently.
since chrome drivers have changed.

**Comment by StreamAlpha** [comment]
please update to latest version
`pip install --upgrade --no-cache-dir git+https://github.com/StreamAlpha/tvdatafeed.git`
