### ISSUE TITLE
nonlogin method issue on Amazon web services

### ISSUE THREAD

**Issue by prathameshjoshi** [StreamAlpha/tvdatafeed#22]
> error Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="overlap-manager-root"]/div/span/div[1]/div/div/div[1]/div[2]/div"}
>   (Session info: headless chrome=91.0.4472.101)
> 
> you are using nologin method, data you access may be limited

i am running script on aws with ubuntu running. Above error is reflecting on terminal. However on my local machine script works fine.. any reason why this is happening? do i need to install any libraries?

**Comment by StreamAlpha** [comment]
since it uses selenium login, on any web services it will work in nologin mode only

**Comment by prathameshjoshi** [comment]
so what is the alternative?

**Comment by carlitoselmago** [comment]
getting the same error

**Comment by prathameshjoshi** [comment]
updated to latest version and token system works great. Issue sorted

**Comment by paras-1991** [comment]
I am trying to run this on AWS lambda but getting following error:
######
[ERROR] FileNotFoundError: [Errno 2] No such file or directory: '/home/sbx_user1051/.tv_datafeed/'
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 8, in lambda_handler
    tv = TvDatafeed(username =username, password=password)
  File "/opt/python/lib/python3.8/site-packages/tvDatafeed/main.py", line 142, in __init__
    self.__assert_dir()
  File "/opt/python/lib/python3.8/site-packages/tvDatafeed/main.py", line 76, in __assert_dir
    os.mkdir(self.path)END
#######
I think it is not ablle to install chromedriver. maybe I need to change some path..I am stuck here..any help/guidance on this.

**Comment by StreamAlpha** [comment]
before initializing tvdatafeed, run the following code-
```python
import os
from tvDatafeed import TvDatafeed,Interval
app_dir=os.mkdir(os.path.join(os.path.expanduser("~"), ".tv_datafeed/"))
if not os.path.exists(app_dir):
    os.mkdir(app_dir)

tv=TvDatafeed()

# your code goes here
```

This will only work without username and password. You will be able to download most of the data without logging in

**Comment by paras-1991** [comment]
thanks for such qucik response. I am still not able to get past the same error;

Response
{
  "errorMessage": "[Errno 2] No such file or directory: '/home/sbx_user1051/.tv_datafeed/'",
  "errorType": "FileNotFoundError",
  "stackTrace": [
    "  File \"/var/task/lambda_function.py\", line 11, in lambda_handler\n    app_dir=os.mkdir(os.path.join(os.path.expanduser(\"~\"), \".tv_datafeed/\"))\n"
  ]
}

Function Logs
START RequestId: 38fba4b8-18a5-47e0-90e1-a2d52afe647 Version: $LATEST
[ERROR] FileNotFoundError: [Errno 2] No such file or directory: '/home/sbx_user1051/.tv_datafeed/'
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 11, in lambda_handler
    app_dir=os.mkdir(os.path.join(os.path.expanduser("~"), ".tv_datafeed/"))END RequestId: 38fba4b8-18a5-47e-90e1-a2d5c2afe647

**Comment by StreamAlpha** [comment]
can you check if below works
```python
import os
import tempfile
from tvDatafeed import TvDatafeed,Interval

app_dir=tempfile.TemporaryDirectory()
if not os.path.exists(app_dir):
    os.mkdir(app_dir)

TvDatafeed.path=app_dir
tv=TvDatafeed()

# your code goes here
```

**Comment by paras-1991** [comment]
still getting error.. I will try to initialize chromium driver and pass its path to chromedrive_path parameter in tvdatafeed. hoping that will resolve the issue. But now facing issue with chromium on python3.8.
if you are able to initialize tvdatafeed on aws lambda do let me know.. and if i am able to solve this i will surely post here.

**Comment by StreamAlpha** [comment]
I am using this on heroku dyno and its working fine. I am not familiar with aws lambda, looks like it has read only file system and does not support creating directories.

The issue seems in creating the temporary directory. Without login chromedriver is not required.
To fix this try creating some folder which you can access with script and set its path in tvdatafeed.
```python
app_dir="any_folder_which_can_be_accessed_by_script"
if not os.path.exists(app_dir):
    os.mkdir(app_dir)

TvDatafeed.path=app_dir
```

**Comment by StreamAlpha** [comment]
on aws lambda `/tmp` is writeable
```python
app_dir = "/tmp/.tv_datafeed/"
if not os.path.exists(app_dir):
    os.mkdir(app_dir)

TvDatafeed.path = app_dir
```
