### ISSUE TITLE
Incorrect date

### ISSUE THREAD

**Issue by younggotti** [StreamAlpha/tvdatafeed#23]
Hi,
I have a strange issue with daily data of Japanese futures: the data I get in Python is back shifted by 1 day, compared to the data I see from the chart on the website:

So, for example for  OSE:NKVIM2021:
- on the website the close price on Friday 4 June 2021 is 20.25 https://www.tradingview.com/chart/?symbol=NKVIM2021
- in Python I don't have a price for that date and 20.25 is the close price on Thursday 3 June 

My code is:

```
from tvDatafeed import TvDatafeed,Interval
tv = TvDatafeed(chromedriver_path="C:\\WebDriver\\bin\\chromedriver.exe")
data= tv.get_hist(symbol='NKVIM2021',exchange='OSE',interval=Interval.in_daily,n_bars=100)

```
(I have the same issue if I access with username and password)

![website](https://user-images.githubusercontent.com/87848617/128766824-0f5a8095-03e2-47ac-a6e4-336aaf3d26e8.png)
![python](https://user-images.githubusercontent.com/87848617/128766839-8329964c-b2c4-4a7b-b60a-4e3b93115103.png)

When timeframe interval is 1 hour, the data looks correct.

**Comment by younggotti** [comment]
> this seems like a timezone issue. I don't see row for 4th Jun in dataframe.

So you have the same issue? (4th Jun on the chart but not in df)
I thought it was a timezone issue too, so on the website I tried playing with different timezones (both in the drop down list in the bottom and in the chart properties menu). But with any timezone, 4th Jun is shown on the chart. So I can't get why it's not in df

**Comment by younggotti** [comment]
The problem seems to occur with all Asian futures markets.
For example, for HKEX: MCH1! the closing price of Friday 13 August (9355) in the dataframe is incorrectly reported as the closing price of Thursday 12.

Looking at the 1-minute data from the TV website chart, that closing price (9355) is the price that was recorded on the 13th at 16:29 exchange time (which is the end of the day trading session for HKEX). The only time zone where that time was still Thursday 12th is UCT-10 (Honolulu).

The other odd thing is that the problem seems to only occur with futures. I made some tests with TSE stocks and the data looks correct. Maybe it depends on the fact that the futures have night/ATH sessions?

**Comment by StreamAlpha** [comment]
change timezone from charts page. it worked for me 

![image](https://user-images.githubusercontent.com/59556194/133738947-690073d0-b072-40db-94a4-e8171aa23d38.png)
