### ISSUE TITLE
Permission Error

### ISSUE THREAD

**Issue by aashutosh-bhattad** [StreamAlpha/tvdatafeed#29]
PermissionError                           Traceback (most recent call last)
~/anaconda3/envs/tv/lib/python3.9/site-packages/selenium/webdriver/common/service.py in start(self)
     71             cmd.extend(self.command_line_args())
---> 72             self.process = subprocess.Popen(cmd, env=self.env,
     73                                             close_fds=platform.system() != 'Windows',

~/anaconda3/envs/tv/lib/python3.9/subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, user, group, extra_groups, encoding, errors, text, umask)
    950 
--> 951             self._execute_child(args, executable, preexec_fn, close_fds,
    952                                 pass_fds, cwd, env,

~/anaconda3/envs/tv/lib/python3.9/subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, gid, gids, uid, umask, start_new_session)
   1820                         err_msg = os.strerror(errno_num)
-> 1821                     raise child_exception_type(errno_num, err_msg, err_filename)
   1822                 raise child_exception_type(err_msg)

PermissionError: [Errno 13] Permission denied: '/home/x/.tv_datafeed/'

During handling of the above exception, another exception occurred:

WebDriverException                        Traceback (most recent call last)
~/anaconda3/envs/tv/lib/python3.9/site-packages/tvDatafeed/main.py in __webdriver_init(self)
    247 
--> 248             driver = webdriver.Chrome(
    249                 self.chromedriver_path, desired_capabilities=caps, options=options

~/anaconda3/envs/tv/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py in __init__(self, executable_path, port, options, service_args, desired_capabilities, service_log_path, chrome_options, keep_alive)
     72             log_path=service_log_path)
---> 73         self.service.start()
     74 

~/anaconda3/envs/tv/lib/python3.9/site-packages/selenium/webdriver/common/service.py in start(self)
     85             elif err.errno == errno.EACCES:
---> 86                 raise WebDriverException(
     87                     "'%s' executable may have wrong permissions. %s" % (

WebDriverException: Message: '' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home

During handling of the above exception, another exception occurred:

UnboundLocalError                         Traceback (most recent call last)
/tmp/ipykernel_16052/1741820756.py in <module>
----> 1 tv= TvDatafeed(auto_login=False)

~/anaconda3/envs/tv/lib/python3.9/site-packages/tvDatafeed/main.py in __init__(self, username, password, chromedriver_path, auto_login)
    135 
    136         token = None
--> 137         token = self.auth(username, password)
    138 
    139         if token is None:

~/anaconda3/envs/tv/lib/python3.9/site-packages/tvDatafeed/main.py in auth(self, username, password)
    210 
    211         else:
--> 212             driver = self.__login(username, password)
    213             if driver is not None:
    214                 token = self.__get_token(driver)

~/anaconda3/envs/tv/lib/python3.9/site-packages/tvDatafeed/main.py in __login(self, username, password)
    150     def __login(self, username, password):
    151 
--> 152         driver = self.__webdriver_init()
    153 
    154         if not self.__automatic_login:

~/anaconda3/envs/tv/lib/python3.9/site-packages/tvDatafeed/main.py in __webdriver_init(self)
    258 
    259         except Exception as e:
--> 260             driver.quit()
    261             logger.error(e)
    262 

UnboundLocalError: local variable 'driver' referenced before assignment

**Comment by aashutosh-bhattad** [comment]
how to resolve this?

**Comment by StreamAlpha** [comment]
https://github.com/StreamAlpha/tvdatafeed/issues/26#issuecomment-912619033
