### ISSUE TITLE
Random ValueError: could not convert string to float: '}' 

### ISSUE THREAD

**Issue by younggotti** [StreamAlpha/tvdatafeed#30]
Hi,
When  running this code:
```
tv=TvDatafeed(username, password, chromedriver_path="C:\\WebDriver\\bin\\chromedriver.exe", auto_login=False)
data=tv.get_hist(symbol='SE02Y',exchange="TVC",interval=Interval.in_daily, n_bars=100)
```
sometimes I get this error:
```
ValueError: could not convert string to float: '}' 

~\anaconda3\lib\site-packages\tvDatafeed\main.py in get_hist(self, symbol, exchange, interval, n_bars, fut_contract)
    474                 break
    475 
--> 476         return self.__create_df(raw_data, symbol)
    477 
    478 

~\anaconda3\lib\site-packages\tvDatafeed\main.py in __create_df(raw_data, symbol)
    353                     float(xi[7]),
    354                     float(xi[8]),
--> 355                     float(xi[9]),
    356                 ]
    357             )

ValueError: could not convert string to float: '}'
```

I cannot find a pattern that explains why sometimes it works and sometimes it doesn't.  It looks just random.
When using different securities I don't have the same issue
Any help?
Thanks

**Comment by bentobit8** [comment]
sometimes xi[9] is empty which is string and give ValueError once we put into float().
what I did is check if xi[9] is string and give 0 value to it.

example

try:
    float(xi[9])
except ValueError:
    xi[9]=0

**Comment by StreamAlpha** [comment]
Check the symbol/exchange is valid, this happens when symbol entered is invalid.

**Comment by Nathantse013** [comment]
> sometimes xi[9] is empty (which is string) and give ValueError once we put into float(). what I did is check if xi[9] is string and give 0 value to it.
> 
> example
> 
> ```
> try:
>     float(xi[9])
> except ValueError:
>     xi[9]=0
> ```

May I know where should I edit this?

**Comment by Nathantse013** [comment]
> symbol

The symbol/exchange is valid, however the error appears randomly.
According the previous comment, the volume showed 0 sometimes?

**Comment by aeneaswiener-admin** [comment]
This happens intermittently and only for tickers which do not have volume, e.g. ISM:MAN_PMI, and TVC:VIX

Any chance you could address it in a fix?

**Comment by pssrujan1999** [comment]
> ~\anaconda3\lib\site-packages\tvDatafeed\main.py in __create_df(raw_data, symbol)
>     353                     float(xi[7]),
>     354                     float(xi[8]),
> --> 355                     float(xi[9]),
>     356                 ]
>     357             )

Deleting the statement in line 355 solves the problem, but without the volume data

**Comment by pssrujan1999** [comment]
> > > ~\anaconda3\lib\site-packages\tvDatafeed\main.py in __create_df(raw_data, symbol)
> > > 353                     float(xi[7]),
> > > 354                     float(xi[8]),
> > > --> 355                     float(xi[9]),
> > > 356                 ]
> > > 357             )
> > 
> > 
> > Deleting the statement in line 355 solves the problem, but without the volume data
> 
> for me this triggers a new error in the construction.py: ValueError: 6 columns passed, passed data had 5 columns
> 
> my fix is to pass xi[9] = 0 example:
> 
> ```
> for xi in x:
>                 xi = re.split("\[|:|,|\]", xi)
> --------->      xi[9] = 0
>                 ts = datetime.datetime.fromtimestamp(float(xi[4]))
>                 data.append(
>                     [
>                         ts,
>                         float(xi[5]),
>                         float(xi[6]),
>                         float(xi[7]),
>                         float(xi[8]),
>                         float(xi[9])
> ```
> 
> However this one also means the volume column equals to zero.

![temp](https://user-images.githubusercontent.com/61612623/179360605-9df3a28e-75c0-4016-aa5c-f5dd70563417.JPG)

I have changed code in the main file in these places(deleted volume column)....it worked

**Comment by StreamAlpha** [comment]
fixed in the latest release. install from github
