### ISSUE TITLE
Another Chrome Driver issue

### ISSUE THREAD

**Issue by BoeingConstrictor** [StreamAlpha/tvdatafeed#31]
I am using the pycharm IDE, and I am continually getting the "do you want to install chromedriver?? y/n" prompt, even after having installed it. The code does not work after that. Suggestions?

Thanks!

**Comment by StreamAlpha** [comment]
pycharm by default makes a new environment for project.

it might be happening that you are installing in one and using other environment for the project

make sure the environment in both cases are same
