### ISSUE TITLE
How can I install Selenium driver on ReplIt?

### ISSUE THREAD

**Issue by DROBNJAK** [StreamAlpha/tvdatafeed#32]
I want to run my TradingView download code from an online Python code hosting service called ReplIt.com.

If one needs to install Chromium browser in order to get that Selenium driver, that one can forget about running his code from Python hosted online ... Is there any workaround so one can get Selenium without installing Chromium?

Can that Selenium be replaced with something that doesn't need Chromium? Why is Selenium needed at all, when Yahoo Finance Python library can work without Selenium?

**Comment by StreamAlpha** [comment]
fixed in the latest release. install from github
