### ISSUE TITLE
Error using tv = TvDatafeed(auto_login=False)

### ISSUE THREAD

**Issue by comp1810** [StreamAlpha/tvdatafeed#33]
```
from tvDatafeed import TvDatafeed, Interval
tv = TvDatafeed(auto_login=False)


----> 4 tv = TvDatafeed(auto_login=False)

TypeError: __init__() got an unexpected keyword argument 'auto_login'
```

getting this error, am I doing something wrong here?

**Comment by StreamAlpha** [comment]
uninstall previous version and install using-
`pip install --upgrade --no-cache-dir git+https://github.com/StreamAlpha/tvdatafeed.git`

or check this out, this is a hard reset procedure-
https://github.com/StreamAlpha/tvdatafeed/issues/26#issuecomment-912619033
