### ISSUE TITLE
After enter all data it show no login details

### ISSUE THREAD

**Issue by Praveen96958127** [StreamAlpha/tvdatafeed#36]

**Comment by StreamAlpha** [comment]
Please provide sufficient details. Read this before creating an issue
https://github.com/StreamAlpha/tvdatafeed#read-this-before-creating-an-issue

Most of the issues can be resolved by installing most updated version and hard reset as explained here-
https://youtu.be/f76dOZW2gwI

**Comment by undomained** [comment]
https://github.com/StreamAlpha/tvdatafeed/pull/39
