### ISSUE TITLE
developer branch unexpected keyworld argument 'auto_login' and main branch SSL error code 1

### ISSUE THREAD

**Issue by daszzzpg** [StreamAlpha/tvdatafeed#37]
I was experiencing a similar issue. whose main syndrome is like this https://github.com/StreamAlpha/tvdatafeed/issues/1
ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -100
So I follow the fix by upgrade my tvdatafeed to a developer branch
pip install --upgrade --no-cache-dir git+https://github.com/StreamAlpha/tvdatafeed.git@develop

However, it lead to another error
Traceback (most recent call last):
  File "f:\tvpy\tvfeed.py", line 2, in <module>
    tv = TvDatafeed(auto_login=False)
TypeError: __init__() got an unexpected keyword argument 'auto_login'

All codes to produce this error
```
from tvDatafeed import TvDatafeed,Interval
tv = TvDatafeed(auto_login=False)
```

For this SSL error I don't know what caused it. Is it related to my using SSL proxy?
If so, how do I fix it?

**Comment by StreamAlpha** [comment]
install from main repository using
```
pip install --upgrade --no-cache-dir git+https://github.com/StreamAlpha/tvdatafeed.git
```

in case of any error start fresh as described here-
https://github.com/StreamAlpha/tvdatafeed/issues/26#issuecomment-912619033
