### ISSUE TITLE
no such element: Unable to locate element: {"method":"link text","selector":"Sign in"}

### ISSUE THREAD

**Issue by mohsennaserikish** [StreamAlpha/tvdatafeed#38]
Hello,
when I run this line :
tv=TvDatafeed(username=username,password=password)
I get this error message:
no such element: Unable to locate element: {"method":"link text","selector":"Sign in"}
could you please help me?
Thank you

**Comment by StreamAlpha** [comment]
use the manual login as explained in this tutorial-

https://youtu.be/f76dOZW2gwI
