### ISSUE TITLE
Couldn't install (upgrade from v1.0.4) 

### ISSUE THREAD

**Issue by makenahub** [StreamAlpha/tvdatafeed#40]
Dear all.
Unfortunately, I couldn't install (upgrade from v1.0.4) this lib with 
pip install --upgrade --no-cache-dir git+https://github.com/StreamAlpha/tvdatafeed.git
:(

The Error message occurred as follows:
(base) Man@MacBook-Pro-ght-340 ~ % pip install --upgrade --no-cache-dir git+https://github.com/StreamAlpha/tvdatafeed.git
Collecting git+https://github.com/StreamAlpha/tvdatafeed.git
  Cloning https://github.com/StreamAlpha/tvdatafeed.git to /private/var/folders/qt/4wsb0cvd637_6fk9m951hdrc0000gn/T/pip-req-build-kjhnth9b
  Running command git clone -q https://github.com/StreamAlpha/tvdatafeed.git /private/var/folders/qt/4wsb0cvd637_6fk9m951hdrc0000gn/T/pip-req-build-kjhnth9b
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
WARNING: Discarding git+https://github.com/StreamAlpha/tvdatafeed.git. Command errored out with exit status 1: git clone -q https://github.com/StreamAlpha/tvdatafeed.git /private/var/folders/qt/4wsb0cvd637_6fk9m951hdrc0000gn/T/pip-req-build-kjhnth9b Check the logs for full command output.
ERROR: Command errored out with exit status 1: git clone -q https://github.com/StreamAlpha/tvdatafeed.git /private/var/folders/qt/4wsb0cvd637_6fk9m951hdrc0000gn/T/pip-req-build-kjhnth9b Check the logs for full command output.

**Comment by StreamAlpha** [comment]
this seems like a git issue not tvdatafeed, you can check the similar issue here 
https://stackoverflow.com/questions/52522565/git-is-not-working-after-macos-update-xcrun-error-invalid-active-developer-pa

as a temporary solution, clone this git or download zip and extract, uninstall the existing version. After that, from the extracted folder, run the following command to install
`pip install -e .`

**Comment by makenahub** [comment]
Thank you very much. I resolved git-issue and managed to update TvDatafeed to 1.2.0. 
For now, I got another one with Autologin=True o False it doesn't matter. The program returns "UnboundLocalError: local variable 'driver' referenced before assignment" :(
Trying to resolve it with another corresponding issue-link here.
