### ISSUE TITLE
Is there anyway to get other than bar chart from tradingview

### ISSUE THREAD

**Issue by alfredkosasihh** [StreamAlpha/tvdatafeed#41]
Hi StreamAlpha,

thankyou for providing us with the tools for scraping Tradingview website price data, I'm wondering is there anyway to retrieve other chart price data other than bar chart (Heikin Ashi) price data?

**Comment by StreamAlpha** [comment]
Heikin Ashi can be calculated using the ohlc data from tvdatafeed. Check out this post for procedure-
https://towardsdatascience.com/how-to-calculate-heikin-ashi-candles-in-python-for-trading-cff7359febd7

**Comment by alfredkosasihh** [comment]
> Heikin Ashi can be calculated using the ohlc data from tvdatafeed. Check out this post for procedure- https://towardsdatascience.com/how-to-calculate-heikin-ashi-candles-in-python-for-trading-cff7359febd7

thankyou for the answear
