### ISSUE TITLE
Issue to use this library in docker

### ISSUE THREAD

**Issue by TMoum** [StreamAlpha/tvdatafeed#45]
Hello,
First of all thank you for sharing your work.

I would like to use it inside a docker container. However it crash because I can't answer the question for chromedriver.
Is there any solution?
`"\n\ndo you want to install chromedriver automatically?? y/n\t"`

Regards,

Thomas

**Comment by StreamAlpha** [comment]
https://github.com/StreamAlpha/tvdatafeed/issues/22#issuecomment-1008577408
