### ISSUE TITLE
error when symbol name not found in database

### ISSUE THREAD

**Issue by akshaythakker** [StreamAlpha/tvdatafeed#49]
Hi StreamAplha:
Firstly many many thanks for building this code. Its super helpful!! I am facing two issues in the code when the name of the symbol I sent is not in the list of securities of that exchange. With the very limited knowledge I have of python, I did try to modify your code a little, but I fell short and hence listing it out here. 
First instead of throwing up an exception - which as you can see in the sample code will atleast allow me to debug and correct just returns a None
Second, it waits for almost 80 seconds to throw up the Error and hence holds up the other part of the code I am incorporating this into for that much time. 

Sample code is 
```
from tvDatafeed import TvDatafeed, Interval
import timeit

username = 'xxxx'
password = 'xxxx'


tv = TvDatafeed(username, password, chromedriver_path='./chromedriver')
security_name = 'BAJAJ-AUTO1!'
exchange = 'NSE'
number_of_bars = 1

starttime = timeit.default_timer()
try:
    data_recv = tv.get_hist(symbol=security_name, exchange=exchange, interval=Interval.in_5_minute, n_bars=number_of_bars)
    print(data_recv)
except AttributeError:
    print(f"error in getting data for {security_name}")
print("The time difference is :", timeit.default_timer() - starttime)
```

Output for the above code:
```
None
The time difference is : 81.035164397
ERROR:tvDatafeed.main:Connection to remote host was lost.
ERROR:tvDatafeed.main:no data, please check the exchange and symbol

Process finished with exit code 0
```

Output if just change the security_name to `BAJAJ_AUTO1!`
```                              
                               symbol    open  ...    close   volume
datetime                                       ...                  
2022-03-31 15:25:00  NSE:BAJAJ_AUTO1!  3666.7  ...  3677.05  32750.0

[1 rows x 6 columns]
The time difference is : 8.086900235

Process finished with exit code 0
```

**Comment by StreamAlpha** [comment]
For the symbols with a hyphen (-) or &, try searching symbol in tradingview website first.
Like for this its BAJAJ_AUTO1

And same for M&M

there is no built-in methods to check symbol name. So when invalid symbol is requested, it just waits for socket close.

hope that helps
