### ISSUE TITLE
How to access datetime of index (2022-02-01 11:15) Error: AttributeError: 'DatetimeIndex' object has no attribute 'datetime

### ISSUE THREAD

**Issue by techfor** [StreamAlpha/tvdatafeed#52]
Trying to filter data using specific time of day i.e get row when index == 2022-02-01 11:15

I tried using 
**data[data.index.datetime >datetime.datetime(2022,4,8,11,15)]**  
but got error

**data[data.index.datetime >datetime.datetime(2022,4,8,11,15)]  
AttributeError: 'DatetimeIndex' object has no attribute 'datetime**

How can I filter using datetime and not just date  as above. 
Thanks

**Comment by Loxyez** [comment]
I used the following code like this

`from datetime import datetime as dt
date = datetime.datetime(2022,5,12,11,15)
date = date.strftime("%Y-%m-%d %H:%M:%S")
check = data.reset_index()
check[check['datetime'] > date]`

Hope this help!
