### ISSUE TITLE
ERROR:tvDatafeed.main:expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by PerczynskiAdam** [StreamAlpha/tvdatafeed#53]
Hello

I installed Python version 3.9.8:
![image](https://user-images.githubusercontent.com/43667515/166764923-14b4a399-b319-404e-94cf-00c8bedd199c.png)
The same as in the movie:
https://www.youtube.com/watch?v=kENccs0CW18

In created virtual env and i installed TvDatafeed with:
`pip install --upgrade --no-cache-dir git+https://github.com/StreamAlpha/tvdatafeed.git`

My pip freeze looks like this:
```
async-generator==1.10
attrs==21.4.0
certifi==2021.10.8
cffi==1.15.0
chromedriver-autoinstaller==0.3.1
cryptography==37.0.2
h11==0.13.0
idna==3.3
numpy==1.22.3
outcome==1.1.0
pandas==1.4.2
pycparser==2.21
pyOpenSSL==22.0.0
PySocks==1.7.1
python-dateutil==2.8.2
pytz==2022.1
selenium==4.1.3
six==1.16.0
sniffio==1.2.0
sortedcontainers==2.4.0
trio==0.20.0
trio-websocket==0.9.2
tvdatafeed==1.2.1
urllib3==1.26.9
websocket-client==1.3.2
wsproto==1.1.0
```

Screen of how i try to login:
![image](https://user-images.githubusercontent.com/43667515/166782961-5d5acc9d-e6bd-4124-bfca-a7c48540989c.png)

After i clicked "enter" browser is not opening. Additionally i checked directory:
C:\Users\<name>\.tv_datafeed\chrome and it is empty.

Is there any fixed for this?

Login with password don't work as well:

```
tv = TvDatafeed(
    username=environ.get('tv_user'),
    password=environ.get('tv_password'),
    chromedriver_path=None
)
```

Cheers

**Comment by khazaee** [comment]
same too

**Comment by khazaee** [comment]
> Hello
> 
> I installed Python version 3.9.8: ![image](https://user-images.githubusercontent.com/43667515/166764923-14b4a399-b319-404e-94cf-00c8bedd199c.png) The same as in the movie: https://www.youtube.com/watch?v=kENccs0CW18
> 
> In created virtual env and i installed TvDatafeed with: `pip install --upgrade --no-cache-dir git+https://github.com/StreamAlpha/tvdatafeed.git`
> 
> My pip freeze looks like this:
> 
> ```
> async-generator==1.10
> attrs==21.4.0
> certifi==2021.10.8
> cffi==1.15.0
> chromedriver-autoinstaller==0.3.1
> cryptography==37.0.2
> h11==0.13.0
> idna==3.3
> numpy==1.22.3
> outcome==1.1.0
> pandas==1.4.2
> pycparser==2.21
> pyOpenSSL==22.0.0
> PySocks==1.7.1
> python-dateutil==2.8.2
> pytz==2022.1
> selenium==4.1.3
> six==1.16.0
> sniffio==1.2.0
> sortedcontainers==2.4.0
> trio==0.20.0
> trio-websocket==0.9.2
> tvdatafeed==1.2.1
> urllib3==1.26.9
> websocket-client==1.3.2
> wsproto==1.1.0
> ```
> 
> Screen of how i try to login: ![image](https://user-images.githubusercontent.com/43667515/166782961-5d5acc9d-e6bd-4124-bfca-a7c48540989c.png)
> 
> After i clicked "enter" browser is not opening. Additionally i checked directory: C:\Users<name>.tv_datafeed\chrome and it is empty.
> 
> Is there any fixed for this?
> 
> Login with password don't work as well:
> 
> ```
> tv = TvDatafeed(
>     username=environ.get('tv_user'),
>     password=environ.get('tv_password'),
>     chromedriver_path=None
> )
> ```
> 
> Cheers

same too

**Comment by MahtaRs** [comment]
I exactly have this problem.
is there a fix?
did you find any fix?

**Comment by khazaee** [comment]
@MahtaRs This library is not very useful and the author does not try to improve it. There are even a lot of spelling mistakes that Nesson gives from the author's carelessness. In my opinion, do not waste time with this library, and if you need data on currency codes, go to the site address below. 

cryptodatadownload.com

**Comment by StreamAlpha** [comment]
fixed in the latest release. install from github
