### ISSUE TITLE
Chrome driver version autoinstall

### ISSUE THREAD

**Issue by pquan** [StreamAlpha/tvdatafeed#54]
There's currently a problem with this library. It installs an outdated chromedriver by default. I would be much preferred to install a chromedriver compatible with the currently installed chrome browser.

Here's my workaround and dirty patch.

My code;
```
from webdriver_manager.chrome import ChromeDriverManager
driver = webdriver.Chrome(ChromeDriverManager().install())
tv=TvDatafeed(auto_login=False, chromedriver=driver)
```

And the patch to the library. The constructor is:
```
def __init__(
        self,
        username=None,
        password=None,
        chromedriver_path=None,
        chromedriver=None,
        auto_login=True,
    ) -> None:
....
        self.chromedriver = chromedriver
```
Then we change     def __webdriver_init(self): around line 270 like this:
```
            if self.chromedriver is not None:
                driver = self.chromedriver
            else:
                driver = webdriver.Chrome(
                    self.chromedriver_path, desired_capabilities=caps, options=options
                )
```

Sorry for the extremely dirty patch. I hope the idea is clear.

**Comment by StreamAlpha** [comment]
fixed in the latest release. install from github
