### ISSUE TITLE
Missing Element when attempting to auto logging in.

### ISSUE THREAD

**Issue by solinoxgaming** [StreamAlpha/tvdatafeed#55]
Cant get login to run. I am forced to use auto_login=False.

If there anything I am lose from not being logged in?

`Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="overlap-manager-root"]/div/span/div[1]/div/div/div[1]/div[2]/div"}
  (Session info: headless chrome=102.0.5005.63)
Stacktrace:
Backtrace:
	Ordinal0 [0x00B6B8F3+2406643]
	Ordinal0 [0x00AFAF31+1945393]
	Ordinal0 [0x009EC748+837448]
	Ordinal0 [0x00A192E0+1020640]
	Ordinal0 [0x00A1957B+1021307]
	Ordinal0 [0x00A46372+1205106]
	Ordinal0 [0x00A342C4+1131204]
	Ordinal0 [0x00A44682+1197698]
	Ordinal0 [0x00A34096+1130646]
	Ordinal0 [0x00A0E636+976438]
	Ordinal0 [0x00A0F546+980294]
	GetHandleVerifier [0x00DD9612+2498066]
	GetHandleVerifier [0x00DCC920+2445600]
	GetHandleVerifier [0x00C04F2A+579370]
	GetHandleVerifier [0x00C03D36+574774]
	Ordinal0 [0x00B01C0B+1973259]
	Ordinal0 [0x00B06688+1992328]
	Ordinal0 [0x00B06775+1992565]
	Ordinal0 [0x00B0F8D1+2029777]
	BaseThreadInitThunk [0x7609FA29+25]
	RtlGetAppContainerNamedObjectPath [0x77707A7E+286]
	RtlGetAppContainerNamedObjectPath [0x77707A4E+238]
, ('no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="overlap-manager-root"]/div/span/div[1]/div/div/div[1]/div[2]/div"}\n  (Session info: headless chrome=102.0.5005.63)', None, ['Backtrace:', '\tOrdinal0 [0x00B6B8F3+2406643]', '\tOrdinal0 [0x00AFAF31+1945393]', '\tOrdinal0 [0x009EC748+837448]', '\tOrdinal0 [0x00A192E0+1020640]', '\tOrdinal0 [0x00A1957B+1021307]', '\tOrdinal0 [0x00A46372+1205106]', '\tOrdinal0 [0x00A342C4+1131204]', '\tOrdinal0 [0x00A44682+1197698]', '\tOrdinal0 [0x00A34096+1130646]', '\tOrdinal0 [0x00A0E636+976438]', '\tOrdinal0 [0x00A0F546+980294]', '\tGetHandleVerifier [0x00DD9612+2498066]', '\tGetHandleVerifier [0x00DCC920+2445600]', '\tGetHandleVerifier [0x00C04F2A+579370]', '\tGetHandleVerifier [0x00C03D36+574774]', '\tOrdinal0 [0x00B01C0B+1973259]', '\tOrdinal0 [0x00B06688+1992328]', '\tOrdinal0 [0x00B06775+1992565]', '\tOrdinal0 [0x00B0F8D1+2029777]', '\tBaseThreadInitThunk [0x7609FA29+25]', '\tRtlGetAppContainerNamedObjectPath [0x77707A7E+286]', '\tRtlGetAppContainerNamedObjectPath [0x77707A4E+238]', ''])`

**Comment by StreamAlpha** [comment]
fixed in the latest release. install from github
