### ISSUE TITLE
Datafeed call to history data of NIFTY:NSE gives float error

### ISSUE THREAD

**Issue by amolc** [StreamAlpha/tvdatafeed#58]
dd = tv.get_hist(symbol=stock, exchange=sourceexch, interval=Interval.in_3_minute, n_bars=1)
  File "/env/lib/python3.8/site-packages/tvDatafeed/main.py", line 504, in get_hist
    return self.__create_df(raw_data, symbol)
  File "env/lib/python3.8/site-packages/tvDatafeed/main.py", line 376, in __create_df
    float(xi[9]),
ValueError: could not convert string to float: ''

**Comment by abhiquiet** [comment]
I am also getting the error while fetching the data from NIFTY. I can get the data for other scripts, but not NIFTY. 

Error is as under :

File ~/anaconda3/envs/python310/lib/python3.10/site-packages/tvDatafeed/main.py:505, in TvDatafeed.get_hist(self, symbol, exchange, interval, n_bars, fut_contract, extended_session)
    502     if "series_completed" in result:
    503         break
--> 505 return self.__create_df(raw_data, symbol)

File ~/anaconda3/envs/python310/lib/python3.10/site-packages/tvDatafeed/main.py:377, in TvDatafeed.__create_df(raw_data, symbol)
    368     xi = re.split("\[|:|,|\]", xi)
    369     ts = datetime.datetime.fromtimestamp(float(xi[4]))
    370     data.append(
...
    382     data, columns=["datetime", "open", "high", "low", "close", "volume"]
    383 ).set_index("datetime")
    384 data.insert(0, "symbol", value=symbol)

ValueError: could not convert string to float: '}'

**Comment by StreamAlpha** [comment]
fixed in the latest release. install from github
