### ISSUE TITLE
Download of indices stopped working few days ago ...

### ISSUE THREAD

**Issue by DROBNJAK** [StreamAlpha/tvdatafeed#60]
A large number of indices from all the various exchanges stopped downloading and they throw errors. Here are the few of symbol-exchange pairs that are causing problems: 

	VOLQ-NASDAQ, IXIC-NASDAQ, OMRXBOND-NASDAQ, NCI-NASDAQ, CIX100-NASDAQ, 
	
	TNX.P-CBOE, VXD-CBOE, OVX-CBOE, EVZ-CBOE, BFLY-CBOE, 
	
	ADVN.NY-USI, UPVOL.NY-USI, DECL.NY-USI, DNVOL.NY-USI, ADVDEC.NY-USI, ADVDEC.NQ-USI, PCI-USI, PC-USI, TICK-USI, ADVN.NQ-USI, ADVQ-USI, DECL.NQ-USI, DECLQ-USI, ADVDECV.NY-USI, ADD-USI, TRIN.NY-USI, ATHI.NY-USI, ATLO.NY-USI, TVOL-USI, PVSPX-USI, CVSPX-USI, PCCI-USI, UPVOL.NQ-USI, YRHI.NY-USI, DNVOL.NQ-USI, 
	
	BTCUSDLONGS-BITFINEX, BTCUSDSHORTS-BITFINEX, BTCGBPLONGS-BITFINEX, BTCGBPSHORTS-BITFINEX, BTCEURSHORTS-BITFINEX, BTCJPYLONGS-BITFINEX, BTCJPYSHORTS-BITFINEX, ETHUSDLONGS-BITFINEX, ETHUSDSHORTS-BITFINEX, ETHEURLONGS-BITFINEX, ETHEURSHORTS-BITFINEX, ETHGBPLONGS-BITFINEX, ETHBTCLONGS-BITFINEX, BTCEURLONGS-BITFINEX, 
	
	OAC-TSE, BUK100P-CBOEEU, UK100-CAPITALCOM, N100-EURONEXT, NI225-TVC, US30-CAPITALCOM, 0Q5R-XETR, JPYUSD-SAXO, SP500LVOL-SP, HSI-TVC, DJCIGC-DJ

The error shown bellow only occurs if one of the above symbols is used and they are all indices. Other symbols, like stocks, futures, cryptos etc. all work just fine. Indices worked fine as well until few days ago and then they all stopped working on the same day. It must be that TradingVeiw changed something. 

As well, by looking at the error, it seems that TradingVeiw had renamed or removed HTML element you used for login.
- - - - - - - - - - - - 

This is my setup:
  Python v3.8.7 64-bit  |  tvDatafeed  v1.2.1.  |  Chrome & ChromeDriver 103.0.5060.53

This is error thrown:

DevTools listening on ws://127.0.0.1:53744/devtools/browser/65a83704-2dd1-4c83-a92d-99527def9f92
Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="overlap-manager-root"]/div/span/div[1]/div/div/div[1]/div[2]/div"}
  (Session info: headless chrome=103.0.5060.114)
, ('no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="overlap-manager-root"]/div/span/div[1]/div/div/div[1]/div[2]/div"}\n  (Session info: headless chrome=103.0.5060.114)', None, None)
automatic login failed
 Reinitialize tvdatafeed with auto_login=False
you are using nologin method, data you access may be limited

Traceback (most recent call last):
  File "learn_TradingView_API_v1.00.py", line 110, in <module>
    dfTable = objTV.get_hist(symbol= 'VOLQ', exchange= 'NASDAQ', interval= Interval.in_1_minute, n_bars=50)
  File "C:\Work D-PLUS-07\Software\Python\Learning-00\py_venv\lib\site-packages\tvDatafeed\main.py", line 509, in get_hist
    return self.__create_df(raw_data, symbol)
  File "C:\Work D-PLUS-07\Software\Python\Learning-00\py_venv\lib\site-packages\tvDatafeed\main.py", line 381, in __create_df
    float(xi[9]),
ValueError: could not convert string to float: '}'

**Comment by DROBNJAK** [comment]
OK, for anybody who might need it. It seems that TradingView has changed HTML code on its page, so login code needs to be different. Go to wherever you installed tvdatafee, find main.py, inside there find this code: 

                driver.find_element_by_xpath(
                    '//*[@id="overlap-manager-root"]/div/span/div[1]/div/div/div[1]/div[2]/div'
                ).click()

and replace it with this one: 

		driver.find_element_by_xpath(
                    '//*[@id="overlap-manager-root"]/div/span/div[1]/div/div/div/button[1]'
                ).click()

Now code works for me just fine.

**Comment by DROBNJAK** [comment]
OK, I solved the second issue as well. The one where instruments without volume, like indices, were not downloading. Again one would need to go into main.py file find a piece of code and replace it with a new one. Find this piece of code ...

            for xi in x:
                xi = re.split("\[|:|,|\]", xi)
                ts = datetime.datetime.fromtimestamp(float(xi[4]))
                data.append(
                    [
                        ts,
                        float(xi[5]),
                        float(xi[6]),
                        float(xi[7]),
                        float(xi[8]),
                        float(xi[9]),
                    ]
                )

... and replace it with this one:

            for xi in x:
                xi = re.split("\[|:|,|\]", xi)
                ts = datetime.datetime.fromtimestamp(float(xi[4]))
                # 17.07.2022 - Indices don't usually have Volume, because they are not traded. So, code needs two separeate appenders, one for instruments with volume, with x6 elements, and one without volume, with just x5 elements. A symptom of the x5 element one is that it will have a mislplacet curly bracket '}' in the xi[9].
                if ( xi[9] == '}' or xi[9] == '' ):
                  data.append(
                      [
                          ts,
                          float(xi[5]),
                          float(xi[6]),
                          float(xi[7]),
                          float(xi[8]),
                          float("0.0"),
                      ]
                  )
                else:
                  ## original: # xi[9] will normally hold volume figure.
                  data.append(
                      [
                          ts,
                          float(xi[5]),
                          float(xi[6]),
                          float(xi[7]),
                          float(xi[8]),
                          float(xi[9]),
                      ]
                  )

**Comment by anshulthakur** [comment]
> OK, I solved the second issue as well. The one where instruments without volume, like indices, were not downloading. Again one would need to go into main.py file find a piece of code and replace it with a new one. Find this piece of code ...
> 
> ```
>         for xi in x:
>             xi = re.split("\[|:|,|\]", xi)
>             ts = datetime.datetime.fromtimestamp(float(xi[4]))
>             data.append(
>                 [
>                     ts,
>                     float(xi[5]),
>                     float(xi[6]),
>                     float(xi[7]),
>                     float(xi[8]),
>                     float(xi[9]),
>                 ]
>             )
> ```
> 
> ... and replace it with this one:
> 
> ```
>         for xi in x:
>             xi = re.split("\[|:|,|\]", xi)
>             ts = datetime.datetime.fromtimestamp(float(xi[4]))
>             # 17.07.2022 - Indices don't usually have Volume, because they are not traded. So, code needs two separeate appenders, one for instruments with volume, with x6 elements, and one without volume, with just x5 elements. A symptom of the x5 element one is that it will have a mislplacet curly bracket '}' in the xi[9].
>             if ( xi[9] == '}' or xi[9] == '' ):
>               data.append(
>                   [
>                       ts,
>                       float(xi[5]),
>                       float(xi[6]),
>                       float(xi[7]),
>                       float(xi[8]),
>                       float("0.0"),
>                   ]
>               )
>             else:
>               ## original: # xi[9] will normally hold volume figure.
>               data.append(
>                   [
>                       ts,
>                       float(xi[5]),
>                       float(xi[6]),
>                       float(xi[7]),
>                       float(xi[8]),
>                       float(xi[9]),
>                   ]
>               )
> ```

Yes, I've been using a similar implementation to avoid non-float values in the volume field.

**Comment by StreamAlpha** [comment]
fixed in the latest release. install from github
