### ISSUE TITLE
Incorporating RANGE BARS, like "1R", "10R", "100R" & "1000R" into TVdataFeed!

### ISSUE THREAD

**Issue by DROBNJAK** [StreamAlpha/tvdatafeed#61]
I just read on your profile that you have an interest into fluid dynamic. Anybody with such knowledge would be missing out using the edge that only exists in Range Bars.

I've done some digging through JavaScript on TradingView and found this: 

  {var e=["1","3","5","15","30","45","60","120","180","240","1D","1W","1M","1000R","100R","10R","1R"];return m.enabled("widget")?e:(v("10_seconds_interval")?["1S","5S","10S","15S","30S"]:["1S","5S","15S","30S"]).concat(e)}

I don't exactly know what it means, but "1000R","100R","10R","1R" range bars are clearly supported.

I tried downloading them with tvdatafeed ( by adding them to "class Interval(enum.Enum)" and made this call: 

dfTable = objTV.get_hist(symbol= 'AAL', exchange= 'NASDAQ', interval= Interval.in_100R, n_bars=20)

... but got these errors:

  ERROR:tvDatafeed.main:Connection is already closed.
  ERROR:tvDatafeed.main:no data, please check the exchange and symbol
  None

Unfortunatelly, this is a bit out of the reach of my skill level. 

@StreamAlpha Can you possibly ad range bars, like "1000R","100R","10R","1R", to the bars that can be downloaded with tvdatafeed lib? 

That would be fantastic because there are clearly some little known HFT strategies secretly hiding there :-).

**Comment by StreamAlpha** [comment]
you can calculate this values, use mplfinance or similar libraries
