### ISSUE TITLE
Error while initialising the TVDatafeed instance

### ISSUE THREAD

**Issue by abhiquiet** [StreamAlpha/tvdatafeed#62]
I cannot log in with my credentials and get the following error while trying to initialize the TVDataFeed instance.
I have also defined the path of the chrome driver as under :

**`tv=TvDatafeed(TVusername, TVpassword, chromedriver_path="/usr/bin/chromedriver")`**

chromedriver version installed is 103.0.5060.114

Can you please guide me if I am making a mistake in implementation?
the error I am getting is as under:

ERROR:tvDatafeed.main:Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="overlap-manager-root"]/div/span/div[1]/div/div/div[1]/div[2]/div"}
  (Session info: headless chrome=103.0.5060.114)
Stacktrace:
#0 0x55e86c342023 <unknown>
#1 0x55e86c16b228 <unknown>
#2 0x55e86c1a1b77 <unknown>
#3 0x55e86c1a1d41 <unknown>
#4 0x55e86c1d43d4 <unknown>
#5 0x55e86c1bf04d <unknown>
#6 0x55e86c1d20e8 <unknown>
#7 0x55e86c1bef13 <unknown>
#8 0x55e86c19504c <unknown>
#9 0x55e86c196175 <unknown>
#10 0x55e86c383f66 <unknown>
#11 0x55e86c387e2c <unknown>
#12 0x55e86c36fc1e <unknown>
#13 0x55e86c3888b4 <unknown>
#14 0x55e86c364475 <unknown>
#15 0x55e86c3a28e8 <unknown>
#16 0x55e86c3a2a43 <unknown>
#17 0x55e86c3bc593 <unknown>
#18 0x7ffa9cf5b609 <unknown>
, ('no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="overlap-manager-root"]/div/span/div[1]/div/div/div[1]/div[2]/div"}\n  (Session info: headless chrome=103.0.5060.114)', None, ['#0 0x55e86c342023 <unknown>', '#1 0x55e86c16b228 <unknown>', '#2 0x55e86c1a1b77 <unknown>', '#3 0x55e86c1a1d41 <unknown>', '#4 0x55e86c1d43d4 <unknown>', '#5 0x55e86c1bf04d <unknown>', '#6 0x55e86c1d20e8 <unknown>', '#7 0x55e86c1bef13 <unknown>', '#8 0x55e86c19504c <unknown>', '#9 0x55e86c196175 <unknown>', '#10 0x55e86c383f66 <unknown>', '#11 0x55e86c387e2c <unknown>', '#12 0x55e86c36fc1e <unknown>', '#13 0x55e86c3888b4 <unknown>', '#14 0x55e86c364475 <unknown>', '#15 0x55e86c3a28e8 <unknown>', '#16 0x55e86c3a2a43 <unknown>', '#17 0x55e86c3bc593 <unknown>', '#18 0x7ffa9cf5b609 <unknown>', ''])
ERROR:tvDatafeed.main:automatic login failed
 Reinitialize tvdatafeed with auto_login=False 
WARNING:tvDatafeed.main:you are using nologin method, data you access may be limited

**Comment by anshulthakur** [comment]
Please check this with the most recent pull request

https://github.com/StreamAlpha/tvdatafeed/pull/57

**Comment by StreamAlpha** [comment]
fixed in the latest release. install from github
