### ISSUE TITLE
ERROR:tvDatafeed.main:Connection to remote host was lost. ERROR:tvDatafeed.main:no data, please check the exchange and symbol

### ISSUE THREAD

**Issue by HermanRoberth42quack** [StreamAlpha/tvdatafeed#64]
today something seemed to go wrong with tvdatafeed, for multiple symbols and exchanges I get the following
ERROR:tvDatafeed.main:Connection to remote host was lost.
ERROR:tvDatafeed.main:no data, please check the exchange and symbol

I have rebooted the program, uninstalled and reinstalled to tvdatafeed package but still get this error, anyone else getting the same error

**Comment by StreamAlpha** [comment]
this is a symbol issue. need to diagnose urself
