### ISSUE TITLE
Error by autologin

### ISSUE THREAD

**Issue by stefanomorni** [StreamAlpha/tvdatafeed#66]
Hi,

When initializing Tradingview through

tv = TvDatafeed(username=username,password=password) (after having inserted my username and password of course)

i get following error message:

expected str, bytes or os.PathLike object, not NoneType
'NoneType' object has no attribute 'find_element', ("'NoneType' object has no attribute 'find_element'",)
automatic login failed
 Reinitialize tvdatafeed with auto_login=False 
you are using nologin method, data you access may be limited

The active environement packages are:

# Name                    Version                   Build  Channel
asttokens                 2.0.5              pyhd8ed1ab_0    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     22.1.0             pyh71513ae_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                h8ffe710_7    conda-forge
brotli-bin                1.0.9                h8ffe710_7    conda-forge
brotlipy                  0.7.0           py38h294d835_1004    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2022.6.15            h5b45459_0    conda-forge
certifi                   2022.6.15        py38haa244fe_0    conda-forge
cffi                      1.15.1           py38hd8c33c5_0    conda-forge
chromedriver-autoinstaller 0.3.1                    pypi_0    pypi
colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
cryptography              37.0.1           py38h21b164f_0
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
debugpy                   1.6.0            py38h885f38d_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
executing                 0.9.1              pyhd8ed1ab_0    conda-forge
fonttools                 4.34.4           py38h294d835_0    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
gettext                   0.19.8.1          ha2e2712_1008    conda-forge
glib                      2.72.1               h7755175_0    conda-forge
glib-tools                2.72.1               h7755175_0    conda-forge
gst-plugins-base          1.20.3               he07aa86_0    conda-forge
gstreamer                 1.20.3               hdff456e_0    conda-forge
h11                       0.13.0             pyhd8ed1ab_1    conda-forge
icu                       70.1                 h0e60522_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
intel-openmp              2022.1.0          h57928b3_3787    conda-forge
ipykernel                 6.15.1             pyh025b116_0    conda-forge
ipython                   8.4.0            py38haa244fe_0    conda-forge
jedi                      0.18.1           py38haa244fe_1    conda-forge
jpeg                      9e                   h8ffe710_2    conda-forge
jupyter_client            7.3.4              pyhd8ed1ab_0    conda-forge
jupyter_core              4.11.1           py38haa244fe_0    conda-forge
kiwisolver                1.4.4            py38hbd9d945_0    conda-forge
krb5                      1.19.3               h1176d77_0    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libblas                   3.9.0              15_win64_mkl    conda-forge
libbrotlicommon           1.0.9                h8ffe710_7    conda-forge
libbrotlidec              1.0.9                h8ffe710_7    conda-forge
libbrotlienc              1.0.9                h8ffe710_7    conda-forge
libcblas                  3.9.0              15_win64_mkl    conda-forge
libclang                  14.0.6          default_h77d9078_0    conda-forge
libclang13                14.0.6          default_h77d9078_0    conda-forge
libdeflate                1.12                 h8ffe710_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libglib                   2.72.1               h3be07f2_0    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
liblapack                 3.9.0              15_win64_mkl    conda-forge
libogg                    1.3.4                h8ffe710_1    conda-forge
libpng                    1.6.37               h1d00b33_3    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libtiff                   4.4.0                ha17eb64_2    conda-forge
libvorbis                 1.3.7                h0e60522_0    conda-forge
libwebp                   1.2.3                h8ffe710_1    conda-forge
libwebp-base              1.2.3                h8ffe710_2    conda-forge
libxcb                    1.13              hcd874cb_1004    conda-forge
libzlib                   1.2.12               h8ffe710_2    conda-forge
lz4-c                     1.9.3                h8ffe710_1    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
matplotlib                3.5.2            py38haa244fe_1    conda-forge
matplotlib-base           3.5.2            py38he529843_1    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
mkl                       2022.1.0           h6a75c08_874    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
nest-asyncio              1.5.5              pyhd8ed1ab_0    conda-forge
numpy                     1.23.1           py38h223ccf5_0    conda-forge
openjpeg                  2.4.0                hb211442_1    conda-forge
openssl                   1.1.1q               h8ffe710_0    conda-forge
outcome                   1.2.0              pyhd8ed1ab_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.3                    pypi_0    pypi
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 h0e60522_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.2.0            py38hd8e0db4_0    conda-forge
pip                       22.2.1             pyhd8ed1ab_0    conda-forge
ply                       3.11                       py_1    conda-forge
prompt-toolkit            3.0.30             pyha770c72_0    conda-forge
psutil                    5.9.1            py38h294d835_0    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.12.0             pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyqt                      5.15.7           py38h75e37d8_0    conda-forge
pyqt5-sip                 12.11.0          py38h885f38d_0    conda-forge
pysocks                   1.7.1            py38haa244fe_5    conda-forge
python                    3.8.13          h9a09f29_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytz                      2022.1                   pypi_0    pypi
pywin32                   303              py38h294d835_0    conda-forge
pyzmq                     23.2.0           py38h09162b1_0    conda-forge
qt-main                   5.15.4               h467ea89_2    conda-forge
selenium                  4.3.0              pyhd8ed1ab_0    conda-forge
setuptools                63.2.0           py38haa244fe_0    conda-forge
sip                       6.6.2            py38h885f38d_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sniffio                   1.2.0            py38haa244fe_3    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
sqlite                    3.39.2               h8ffe710_0    conda-forge
stack_data                0.3.0              pyhd8ed1ab_0    conda-forge
tbb                       2021.5.0             h2d74725_1    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tornado                   6.2              py38h294d835_0    conda-forge
traitlets                 5.3.0              pyhd8ed1ab_0    conda-forge
trio                      0.21.0           py38haa244fe_0    conda-forge
trio-websocket            0.9.2              pyhd8ed1ab_0    conda-forge
tvdatafeed                1.2.1                    pypi_0    pypi
typing_extensions         4.3.0              pyha770c72_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
unicodedata2              14.0.0           py38h294d835_1    conda-forge
urllib3                   1.26.11            pyhd8ed1ab_0    conda-forge
vc                        14.2                 hb210afc_6    conda-forge
vs2015_runtime            14.29.30037          h902a5da_6    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
websocket-client          1.3.3                    pypi_0    pypi
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0            py38haa244fe_4    conda-forge
wsproto                   1.1.0            py38haa244fe_1    conda-forge
xorg-libxau               1.0.9                hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
zeromq                    4.3.4                h0e60522_1    conda-forge
zlib                      1.2.12               h8ffe710_2    conda-forge
zstd                      1.5.2                h6255e5f_2    conda-forge

Am I doing somthing wrong?
Is anything wrong with the selenium version?

Many thanks for your answer and for sharing this package.

Beste regards

Stefano

**Comment by stefanomorni** [comment]
Sorry, forgot to mentioned that I installed tvdatafeed through:

pip install --upgrade --no-cache-dir git+https://github.com/StreamAlpha/tvdatafeed.git 

so, it should be up to date.

Thx

**Comment by idogit123** [comment]
Did you install the chromedriver?

**Comment by stefanomorni** [comment]
Yes. I did.
To be honest I solved the problem now. I replaced the all login with requests to get the token and got rid of all references to selenium.
It is a lot easier and working.
Thx

**Comment by StreamAlpha** [comment]
Can you create a PR with request login

**Comment by stefanomorni** [comment]
Sorry for my ignorance. What is a PR?


⁣Stefano Morniroli
***@***.***​

Il giorno 2 ago 2022, 04:04, alle ore 04:04, StreamAlpha ***@***.***> ha scritto:

**Comment by StreamAlpha** [comment]
Pull request (PR) let you update the changes in this repo.

If you share the code for requests login, I can update the code here in this repo so that everyone can use the updated login.

**Comment by StreamAlpha** [comment]
fixed in the latest release. install from Github.

thanks, for bringing this piece of code. **credits given**


![image](https://user-images.githubusercontent.com/59556194/183263331-0b949ef1-7ad7-445d-b7cc-11fd9b4a465e.png)

**Comment by anshulthakur** [comment]
Great contribution, @stefanomorni !
There's one edge case that sometimes occurs on that webpage, typically when you are using your machine from a different IP. It sometimes presents a ReCaptcha challenge. So, in case that starts to happen and login doesn't work, please try to login manually with the same credentials from the browser first and then try doing it using the code.

**Comment by stefanomorni** [comment]
Hi Anshul

 

Thank you for the appreciation and warning concerning the edge case. Will keep it in mind.

 

 

Stefano Morniroli
***@***.*** ***@***.***> 

 

Da: Anshul Thakur ***@***.***> 
Inviato: domenica, 7 agosto 2022 06:30
A: StreamAlpha/tvdatafeed ***@***.***>
Cc: Stefano ***@***.***>; Mention ***@***.***>
Oggetto: Re: [StreamAlpha/tvdatafeed] Error by autologin (Issue #66)

 

Great contribution, @stefanomorni <https://github.com/stefanomorni>  !
There's one edge case that sometimes occurs on that webpage, typically when you are using your machine from a different IP. It sometimes presents a ReCaptcha challenge. So, in case that starts to happen and login doesn't work, please try to login manually with the same credentials from the browser first and then try doing it using the code.
