### ISSUE TITLE
Service.__init__() got an unexpected keyword argument 'verbose'

### ISSUE THREAD

**Issue by moremah** [StreamAlpha/tvdatafeed#68]
Service.__init__() got an unexpected keyword argument 'verbose'
'NoneType' object has no attribute 'find_element', ("'NoneType' object has no attribute 'find_element'",)
automatic login failed
 Reinitialize tvdatafeed with auto_login=False
you are using nologin method, data you access may be limited

**Comment by moremah** [comment]
Hello,
pip install --upgrade --no-cache-dir git+https://github.com/StreamAlpha/tvdatafeed.git
doesn't works

**Comment by Civilians2002** [comment]
I got the same problem. Can't find the cause

**Comment by StreamAlpha** [comment]
fixed in the latest release. install from github
