### ISSUE TITLE
Error installing version tvdatafeed 2.0.0 in Heroku Server

### ISSUE THREAD

**Issue by kool4u** [StreamAlpha/tvdatafeed#72]
When trying to upgrade the version to 2.0.0 in the Heroku server, it gives below error

```
ERROR: Could not find a version that satisfies the requirement tvdatafeed==2.0.0 (from versions: 1.0.2, 1.0.3, 1.0.4, 1.2.1)
ERROR: No matching distribution found for tvdatafeed==2.0.0
```

How do I fix this?

**Comment by StreamAlpha** [comment]
you need to install it from github. add following requirements.txt

`git+https://github.com/StreamAlpha/tvdatafeed.git`

**Comment by kool4u** [comment]
Thank you so much
