### ISSUE TITLE
Not able to get data for some Continuous futures contracts

### ISSUE THREAD

**Issue by AdityaMNayak** [StreamAlpha/tvdatafeed#76]
I used the example code in the docs:

`crudeoil_data = tv.get_hist(symbol='CRUDEOIL', exchange='MCX',
                            interval=Interval.in_1_hour, n_bars=5000, fut_contract=1)`

This results in the cell continuously running till the connection is timed out.
Alternatively I also tried some variations(Changed the symbol to reflect what's shown in tradingview:

`crudeoil_data = tv.get_hist(symbol='CRUDEOIL1!', exchange='MCX',
                            interval=Interval.in_1_hour, n_bars=5000, fut_contract=1)`

Still doesn't seem to do the job. Nifty monthly futures however does work, and data is fetched.
Any clue what the issue could be?

Note : I'm using the no login method, not sure if that could be related.

Thanks.

**Comment by StreamAlpha** [comment]
for mcx data, you need to log in.
