### ISSUE TITLE
use other web readers as driver

### ISSUE THREAD

**Issue by advxx** [StreamAlpha/tvdatafeed#77]
How do I change from Chrome driver to safari web driver ?

**Comment by StreamAlpha** [comment]
no need. install latest version from github

**Comment by advxx** [comment]
Is it possible to change driver ? I can't seem to find an answer
Also could you add 8 and 9 hour to the timeframes available? Thank you so much for invaluable work.

**Comment by AGG2017** [comment]
Latest version do not use a web driver at all. It uses the request library. So, no need to use this or that web driver anymore. The problem for me is that every time I download anything from TradingView I receive a email from them that someone is using my credentials. I tried to add all elements from the browser header to the new request but no success. Maybe the missing cookies or something else is the problem.
