### ISSUE TITLE
ERROR:tvDatafeed.main:Connection is already closed.

### ISSUE THREAD

**Issue by Narayan-030** [StreamAlpha/tvdatafeed#8]

**Comment by allanaguiar** [comment]
Please, I need a help! This error ocorred for me too. ;(

**Comment by allanaguiar** [comment]
Extract the folder tvDatafeed ( zip file in this url: https://drive.google.com/file/d/17TlMcnqCRwA0EJvnrU_NHHcFuFbZT0oO/view?usp=sharing ) in c:(...)anaconda folder(...)/ Lib/site-packages

< thats all right > :) uhuuuulllll :)

**Comment by StreamAlpha** [comment]
update to latest version
