### ISSUE TITLE
Code shows errors

### ISSUE THREAD

**Issue by gbsidh** [StreamAlpha/tvdatafeed#9]
Code shows errors 
![IMG_20210630_080942.jpg](https://user-images.githubusercontent.com/69956062/123893740-968d1d00-d97a-11eb-9182-4de288cde340.jpg)

**Comment by allanaguiar** [comment]
Extract the folder tvDatafeed ( zip file in this url: https://drive.google.com/file/d/17TlMcnqCRwA0EJvnrU_NHHcFuFbZT0oO/view?usp=sharing  ) in c:\(...)anaconda folder(...)/ Lib/site-packages 

<AFTER RESTARD VSCODE >

< thats all right > :) uhuuuulllll :)
